version: '2'
services:
  server:
    image: doorbot-challenge
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - db:/usr/src/app/db
    # Handy for dev
      - ./api:/usr/src/app/api
      - ./webapp:/usr/src/app/webapp
      - ./dist:/usr/src/app/dist
    command: server --watch

  door:
    image: doorbot-challenge
    build: .
    #restart: unless-stopped
    privileged: true
    command: door --insecure --dummy -s server -t "abc123"


volumes:
  db:
